Repository prgrms-web-devcourse/Team-JJINSA-HyperLink-BE, pull requests merged in 2023-02, with the labels that each got.

#8 [#3] Rest Docs Asciidoc 설정
  build.gradle
  src/docs/asciidoc/api.adoc
Labels: Environment

#13 [#4] jacoco report, coverage 설정
  build.gradle
Labels: Environment

#14 [#5] Dev 환경 CI 생성
  .github/workflows/ci.yml
  appspec.yml
  build.gradle
  scripts/deploy.sh
  scripts/start.sh
  scripts/switch.sh
  src/main/java/com/hyperlink/server/global/profile/controller/ProfileController.java
Labels: CI/CD

#16 [#15] Production 환경에 대한 CI/CD 구축
  .github/workflows/ci-prod.yml
Labels: CI/CD

#20 [#19] DB 컬럼명 및 entity 필드명 변경 처리
  src/main/java/com/hyperlink/server/domain/attentionCategory/domain/AttentionCategoryRepository.java
  src/main/java/com/hyperlink/server/domain/attentionCategory/domain/entity/AttentionCategory.java
  src/main/java/com/hyperlink/server/domain/category/domain/CategoryRepository.java
  src/main/java/com/hyperlink/server/domain/company/domain/CompanyRepository.java
  src/main/java/com/hyperlink/server/domain/company/domain/entity/Company.java
  src/main/java/com/hyperlink/server/domain/content/domain/ContentRepository.java
  src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java
  src/main/java/com/hyperlink/server/domain/contentCategory/domain/ContentCategoryRepository.java
  src/main/java/com/hyperlink/server/domain/contentCategory/domain/entity/ContentCategory.java
  src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRepository.java
  src/main/java/com/hyperlink/server/domain/creator/domain/entity/Creator.java
  src/main/java/com/hyperlink/server/domain/creatorCategory/domain/CreatorCategoryRepository.java
  src/main/java/com/hyperlink/server/domain/creatorCategory/domain/entity/CreatorCategory.java
  src/main/java/com/hyperlink/server/domain/member/domain/MemberRepository.java
  src/main/java/com/hyperlink/server/domain/member/domain/entity/Member.java
  src/main/java/com/hyperlink/server/domain/memberContent/domain/MemberContentRepository.java
  src/main/java/com/hyperlink/server/domain/memberContent/domain/entity/MemberContent.java
  src/main/java/com/hyperlink/server/domain/memberContent/domain/entity/MemberContentActionType.java
  src/main/java/com/hyperlink/server/domain/subscription/domain/SubscriptionRepository.java
  src/main/java/com/hyperlink/server/domain/subscription/domain/entity/Subscription.java
  src/main/resources/db/migration/V2__change_column_name.sql
Labels: Environment

#25 [#24] uri 변경으로 인한 ci cd 코드 변경
  .github/workflows/ci-prod.yml
  .github/workflows/ci.yml
  scripts/deploy.sh
  scripts/start.sh
  scripts/switch.sh
Labels: CI/CD

#27 [#26] DB 전체 테이블 PK auto increment 설정 추가
  src/main/resources/db/migration/V3__auto_increment.sql
Labels: Environment

#32 [#30] main 브랜치에 대해 api base uri 변경
  .github/workflows/ci-prod.yml
  .github/workflows/ci.yml
  build.gradle
  lombok.config
  scripts/deploy.sh
  scripts/start.sh
  scripts/switch.sh
  src/main/java/com/hyperlink/server/domain/member/MemberService.java
  src/main/java/com/hyperlink/server/domain/memberContent/domain/entity/MemberContent.java
  src/main/java/com/hyperlink/server/domain/memberContent/domain/entity/MemberContentActionType.java
  src/main/resources/db/migration/V3__auto_increment.sql
Labels: Environment, CI/CD

#40 [#38] jacoco 테스트 빌드 대상 항목 수정
  build.gradle
  src/main/java/com/hyperlink/server/global/exception/GlobalExceptionHandler.java
Labels: Environment

#43 [#42] prod 배포 s3 bucket 삭제
  .github/workflows/ci-prod.yml
Labels: Environment

#44 [#42] prod 배포 s3 bucket 삭제
  .github/workflows/ci-prod.yml
  build.gradle
  src/main/java/com/hyperlink/server/global/exception/GlobalExceptionHandler.java
Labels: Environment

#37 [#35] DB 컬럼 추가 및 컬럼 속성 추가
  src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java
  src/main/resources/db/migration/V4__add_column_inqu.sql
  src/main/resources/db/migration/V5__datetime_auto.sql
Labels: Environment

#45 [#34] 특정 콘텐츠에 대한 조회수 갱신 API 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
  src/main/java/com/hyperlink/server/domain/content/domain/ContentRepository.java
  src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java
  src/main/java/com/hyperlink/server/domain/content/dto/PatchInquiryResponse.java
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
  src/test/java/com/hyperlink/server/content/domain/ContentRepositoryTest.java
Labels: Feature

#53 [#49] Content 테이블 크리에이터 id 컬럼 추가
  src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java
  src/main/resources/db/migration/V6__add_column_category_id.sql
Labels: Environment

#50 [#28] 블로그 글 크롤링 기능 구현
  src/main/resources/crawling-scripts/develop/crawling-d2-develop.js
  src/main/resources/crawling-scripts/develop/crawling-daangn-develop.js
  src/main/resources/crawling-scripts/develop/crawling-kakao-develop.js
  src/main/resources/crawling-scripts/develop/crawling-kurly-develop.js
  src/main/resources/crawling-scripts/develop/crawling-toss-develop.js
  src/main/resources/crawling-scripts/fashion/crawling-vogue-beauty.js
  src/main/resources/crawling-scripts/fashion/crawling-vogue-fashion.js
Labels: Feature

#63 [#60] Content의 카테고리 단일화
  src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java
  src/main/java/com/hyperlink/server/domain/contentCategory/domain/ContentCategoryRepository.java
  src/main/java/com/hyperlink/server/domain/contentCategory/domain/entity/ContentCategory.java
  src/main/java/com/hyperlink/server/domain/creator/domain/entity/Creator.java
  src/main/java/com/hyperlink/server/domain/creatorCategory/domain/CreatorCategoryRepository.java
  src/main/java/com/hyperlink/server/domain/creatorCategory/domain/entity/CreatorCategory.java
  src/main/resources/db/migration/V10__add_column_category_id.sql
Labels: Environment

#64 [#60] Content의 카테고리 단일화
  src/main/resources/db/migration/V11__add_FK_column.sql
Labels: Environment

#70 [#69] Creator, Category 이름 unique로 변경하기
  src/main/java/com/hyperlink/server/domain/category/domain/entity/Category.java
  src/main/java/com/hyperlink/server/domain/creator/domain/entity/Creator.java
  src/main/resources/db/migration/V12__alter_column_creator_category_name.sql
Labels: Environment

#56 [#55] 조회수 갱신 API 리팩토링 및 테스트 코드 수정
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
  src/main/java/com/hyperlink/server/domain/content/domain/ContentRepository.java
  src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java
  src/main/java/com/hyperlink/server/domain/content/dto/PatchInquiryResponse.java
  src/main/java/com/hyperlink/server/domain/creator/domain/entity/Creator.java
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
  src/test/java/com/hyperlink/server/content/domain/ContentRepositoryTest.java
  src/test/java/com/hyperlink/server/memberContent/application/MemberContentServiceIntegrationTest.java
Labels: Test, Refactor

#58 [#46] 검색 API 구현 및 테스트 코드 작성
  build.gradle
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
  src/main/java/com/hyperlink/server/domain/content/domain/ContentRepository.java
  src/main/java/com/hyperlink/server/domain/content/dto/ContentResponse.java
  src/main/java/com/hyperlink/server/domain/content/dto/RecommendationCompanyResponse.java
  src/main/java/com/hyperlink/server/domain/content/dto/SearchResponse.java
  src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
  src/main/java/com/hyperlink/server/domain/memberContent/application/MemberContentService.java
  src/main/java/com/hyperlink/server/global/config/QuerydslConfiguration.java
  src/main/java/com/hyperlink/server/global/exception/GlobalExceptionHandler.java
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
Labels: Feature, Test

#73 [#72] Content 테이블 isViewable 컬럼 추가
  src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java
  src/main/resources/db/migration/V13__add_column_is_viewable.sql
  src/main/resources/db/migration/V14__alter_column_is_viewable.sql
Labels: Environment

#77 [#76] adoc 수정
  src/docs/asciidoc/api.adoc
  src/docs/asciidoc/members.adoc
Labels: Refactor

#83 [#52] Member 테이블에 gender, isAdmin 컬럼 추가
  src/main/java/com/hyperlink/server/domain/member/domain/entity/Member.java
  src/main/resources/db/migration/V15__add_column_gender_and_isadmin.sql
  src/main/resources/db/migration/V16__change_column_name.sql
Labels: Environment

#79 [#59] 비추천 크리에이터 추가 API 구현 및 테스트 작성
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
  src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
  src/main/java/com/hyperlink/server/domain/creator/exception/CreatorNotFoundException.java
  src/main/java/com/hyperlink/server/domain/memberCreator/domain/MemberCreatorRepository.java
  src/main/java/com/hyperlink/server/domain/memberCreator/domain/entity/MemberCreator.java
  src/test/java/com/hyperlink/server/creator/application/CreatorServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
Labels: Feature, Test

#71 [#66] Creator 생성 로직 구현
  src/main/java/com/hyperlink/server/domain/category/domain/CategoryRepository.java
  src/main/java/com/hyperlink/server/domain/category/exception/CategoryNotFoundException.java
  src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
  src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
  src/main/java/com/hyperlink/server/domain/creator/domain/entity/Creator.java
  src/main/java/com/hyperlink/server/domain/creator/dto/CreatorEnrollRequest.java
  src/main/java/com/hyperlink/server/domain/creator/dto/CreatorEnrollResponse.java
  src/test/java/com/hyperlink/server/category/domain/CategoryRepositoryTest.java
  src/test/java/com/hyperlink/server/creator/application/CreatorServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/creator/application/CreatorServiceMockTest.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
Labels: Feature

#90 [#85] DB table 변경
  src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
  src/main/java/com/hyperlink/server/domain/memberCreator/domain/MemberCreatorRepository.java
  src/main/java/com/hyperlink/server/domain/memberHistory/domain/entity/MemberHistory.java
  src/main/java/com/hyperlink/server/domain/notRecommendCreator/domain/NotRecommendCreatorRepository.java
  src/main/java/com/hyperlink/server/domain/notRecommendCreator/domain/entity/NotRecommendCreator.java
  src/main/resources/db/migration/V17__create_table_history_and_alter_table_name_not_recommend.sql
  src/test/java/com/hyperlink/server/creator/application/CreatorServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/creator/application/CreatorServiceMockTest.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
Labels: Feature, Environment
