Repository prgrms-web-devcourse/Team-JJINSA-HyperLink-BE, pull requests merged in 2023-03, with the labels that each got.

#96 [#95] jacoco 커버리지 제외 클래스 경로 오류 수정
  build.gradle
Labels: Environment, Fix

#88 [#74] 로그아웃 api 구현
  src/docs/asciidoc/members.adoc
  src/main/java/com/hyperlink/server/domain/auth/application/AuthService.java
  src/main/java/com/hyperlink/server/domain/auth/controller/AuthController.java
  src/main/java/com/hyperlink/server/domain/auth/token/RefreshTokenRepository.java
  src/main/java/com/hyperlink/server/domain/auth/token/exception/InValidAccessException.java
  src/main/java/com/hyperlink/server/domain/auth/token/exception/RefreshTokenNotExistException.java
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
  src/test/java/com/hyperlink/server/auth/application/AuthServiceTest.java
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java
Labels: Feature

#101 [#100] memberIdArgumentResolver 오류 수정 및 배포 확인에 필요한 uri 필터에서 제외
  src/main/java/com/hyperlink/server/domain/auth/token/AuthTokenExtractor.java
  src/main/java/com/hyperlink/server/global/config/LoginMemberIdArgumentResolver.java
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
Labels: Fix, Refactor

#91 [#57] 크롤링 데이터 DB 업로드 기능 구현
  build.gradle
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/controller/ContentConsumer.java
  src/main/java/com/hyperlink/server/domain/content/domain/ContentRepository.java
  src/main/java/com/hyperlink/server/domain/content/dto/ContentEnrollResponse.java
  src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRepository.java
  src/main/java/com/hyperlink/server/domain/creator/domain/entity/Creator.java
  src/main/java/com/hyperlink/server/domain/memberCreator/domain/entity/MemberCreator.java~[#61] memberCreator table 생성
  src/main/java/com/hyperlink/server/domain/memberCreator/domain/entity/MemberCreator.java~develop/v0.1
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/content/controller/ContentRabbitMQIntegrationTest.java
  src/test/java/com/hyperlink/server/creator/domain/CreatorRepositoryTest.java
Labels: Feature, Fix

#110 Flyway Content 테이블 link 컬럼 길이 변경(증가)
  src/main/resources/db/migration/V18__alter_table_content_column_link_unique_and_increase_length.sql
Labels: Environment

#113 [#111] 인증유저 단위테스트를 위한 setup 클래스 추가
  src/test/java/com/hyperlink/server/memberContent/AuthSetupForMock.java
Labels: Test

#118 [#117] cookie secure값 false로 변경
  src/main/java/com/hyperlink/server/domain/auth/controller/AuthController.java
  src/main/java/com/hyperlink/server/domain/auth/token/RefreshTokenCookieProvider.java
Labels: Fix

#120 [#119] cd 테스트용
  src/main/java/com/hyperlink/server/domain/auth/controller/AuthController.java
Labels: Test

#125 [#124] HOTFIX RabbitMQ 통합 컨트롤러 테스트 수정
  src/test/java/com/hyperlink/server/content/controller/ContentRabbitMQIntegrationTest.java
Labels: Fix

#126 [#122] 멤버 로그인, 회원가입, google oauth api 수정사항 변경
  src/main/java/com/hyperlink/server/domain/auth/application/AuthService.java
  src/main/java/com/hyperlink/server/domain/auth/controller/AuthController.java
  src/main/java/com/hyperlink/server/domain/auth/dto/LoginRequest.java
  src/main/java/com/hyperlink/server/domain/auth/oauth/GoogleAccessToken.java
  src/main/java/com/hyperlink/server/domain/auth/oauth/GoogleOauthClient.java
  src/main/java/com/hyperlink/server/domain/auth/oauth/dto/OauthResponse.java
  src/main/java/com/hyperlink/server/domain/member/application/MemberService.java
  src/main/java/com/hyperlink/server/domain/member/controller/MemberController.java
  src/main/java/com/hyperlink/server/domain/member/dto/SignUpRequest.java
  src/test/java/com/hyperlink/server/auth/application/AuthServiceTest.java
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java
  src/test/java/com/hyperlink/server/global/exception/GlobalExceptionHandlerTest.java
  src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
Labels: Refactor

#97 [#68] 유저 히스토리 내역 저장 기능 구현
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
  src/main/java/com/hyperlink/server/domain/memberHistory/application/MemberHistoryService.java
  src/main/java/com/hyperlink/server/domain/memberHistory/domain/entity/MemberHistoryRepository.java
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
  src/test/java/com/hyperlink/server/memberHistory/application/MemberHistoryIntegrationTest.java
Labels: Feature, Test

#99 [#98] content 도메인 공통 DTO 변경
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/dto/GetContentsCommonResponse.java
  src/main/java/com/hyperlink/server/domain/content/dto/SearchResponse.java
  src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
Labels: Refactor

#105 [#104] 검색 API 최신순으로 정렬 추가, jwt 헤더 적용
  src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
Labels: Feature

#131 [#130] LoginArgumentResolver 문제 해결
  src/main/java/com/hyperlink/server/global/config/LoginMemberIdArgumentResolver.java
Labels: Fix

#93 [#89] accessToken 재발급 api 개발
  build.gradle
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/auth/application/AuthService.java
  src/main/java/com/hyperlink/server/domain/auth/controller/AuthController.java
  src/main/java/com/hyperlink/server/domain/auth/dto/RenewResponse.java
  src/main/java/com/hyperlink/server/domain/auth/dto/RenewResult.java
  src/main/java/com/hyperlink/server/domain/auth/oauth/GoogleAccessToken.java
  src/main/java/com/hyperlink/server/domain/auth/token/AuthTokenExtractor.java
  src/main/java/com/hyperlink/server/domain/auth/token/JwtTokenProvider.java
  src/main/java/com/hyperlink/server/domain/auth/token/RefreshTokenCookieProvider.java
  src/main/java/com/hyperlink/server/domain/auth/token/exception/RefreshTokenNotExistException.java
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/member/domain/Career.java
  src/main/java/com/hyperlink/server/domain/member/domain/CareerYear.java
  src/main/java/com/hyperlink/server/domain/member/domain/entity/Member.java
  src/main/java/com/hyperlink/server/domain/member/dto/SignUpRequest.java
  src/main/java/com/hyperlink/server/domain/member/exception/CareerNotFoundException.java
  src/main/java/com/hyperlink/server/domain/member/exception/CareerYearNotFoundException.java
  src/main/java/com/hyperlink/server/domain/memberHistory/application/MemberHistoryService.java
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
  src/test/java/com/hyperlink/server/attentionCategory/application/AttentionCategoryServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/auth/application/AuthServiceTest.java
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java
  src/test/java/com/hyperlink/server/auth/token/JwtTokenProviderTest.java
  src/test/java/com/hyperlink/server/category/domain/CategoryRepositoryTest.java
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/creator/application/CreatorServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
  src/test/java/com/hyperlink/server/global/exception/GlobalExceptionHandlerTest.java
  src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
  src/test/java/com/hyperlink/server/member/domain/CareerTest.java
  src/test/java/com/hyperlink/server/member/domain/CareerYearTest.java
  src/test/java/com/hyperlink/server/memberContent/AuthSetupForMock.java
  src/test/java/com/hyperlink/server/memberContent/application/MemberContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/memberHistory/application/MemberHistoryIntegrationTest.java
Labels: Feature

#102 [#94] myPage api 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/auth/application/AuthService.java
  src/main/java/com/hyperlink/server/domain/auth/controller/AuthController.java
  src/main/java/com/hyperlink/server/domain/auth/token/AuthTokenExtractor.java
  src/main/java/com/hyperlink/server/domain/member/application/MemberService.java
  src/main/java/com/hyperlink/server/domain/member/controller/MemberController.java
  src/main/java/com/hyperlink/server/domain/member/domain/Career.java
  src/main/java/com/hyperlink/server/domain/member/domain/CareerYear.java
  src/main/java/com/hyperlink/server/domain/member/dto/MyPageResponse.java
  src/test/java/com/hyperlink/server/AuthSetupForMock.java
  src/test/java/com/hyperlink/server/auth/application/AuthServiceTest.java
  src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
  src/test/java/com/hyperlink/server/memberContent/AuthSetupForMock.java
  src/test/java/com/hyperlink/server/memberHistory/controller/MemberHistoryControllerTest.java
Labels: Feature

#108 [#103] 관심목록 변경 api 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/attentionCategory/application/AttentionCategoryService.java
  src/main/java/com/hyperlink/server/domain/attentionCategory/dto/AttentionCategoryRequest.java
  src/main/java/com/hyperlink/server/domain/attentionCategory/dto/AttentionCategoryResponse.java
  src/main/java/com/hyperlink/server/domain/member/application/MemberService.java
  src/main/java/com/hyperlink/server/domain/member/controller/MemberController.java
  src/main/java/com/hyperlink/server/global/config/WebConfig.java
  src/test/java/com/hyperlink/server/AuthSetupForMock.java
  src/test/java/com/hyperlink/server/attentionCategory/application/AttentionCategoryServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerMockTest.java
Labels: Feature

#136 [#114] 크리에이터 삭제(어드민) 기능 구현 및 크리에이터 추가 기능 리팩토링
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
  src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
  src/main/java/com/hyperlink/server/domain/creator/dto/CreatorEnrollResponse.java
  src/test/java/com/hyperlink/server/creator/application/CreatorServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/creator/application/CreatorServiceMockTest.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
  src/test/java/com/hyperlink/server/creator/domain/CreatorRepositoryTest.java
Labels: Feature

#148 [#147] cors preflight를 위한 Opitons 요청을 필터에서 제외
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
Labels: Fix

#132 [#80] 기존 개발 완료된 API에 jwt 헤더 추가, 검색 API 오류 수정
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
  src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
  src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
  src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
  src/main/java/com/hyperlink/server/domain/memberContent/controller/MemberContentController.java
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
  src/test/java/com/hyperlink/server/memberContent/controller/MemberContentControllerTest.java
Labels: Feature, Test, Fix

#141 [#137] 크리에이터 구독 추가/삭제 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
  src/main/java/com/hyperlink/server/domain/subscription/application/SubscriptionService.java
  src/main/java/com/hyperlink/server/domain/subscription/controller/SubscriptionController.java
  src/main/java/com/hyperlink/server/domain/subscription/domain/SubscriptionRepository.java
  src/main/java/com/hyperlink/server/domain/subscription/domain/entity/Subscription.java
  src/main/java/com/hyperlink/server/domain/subscription/dto/SubscribeResponse.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
  src/test/java/com/hyperlink/server/subscription/application/SubscriptionServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/subscription/application/SubscriptionServiceMockTest.java
  src/test/java/com/hyperlink/server/subscription/controller/SubscriptionControllerTest.java
Labels: Feature, Fix

#146 [#142] 어드민 페이지 컨텐츠 활성화 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
  src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
Labels: Feature

#156 [#155] whitelist에 API url 추가
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
Labels: Feature

#154 [#143] 메인 페이지에 보일 컨텐츠 전체보기 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/attentionCategory/domain/AttentionCategoryRepository.java
  src/main/java/com/hyperlink/server/domain/category/domain/CategoryRepository.java
  src/main/java/com/hyperlink/server/domain/common/ContentDtoFactoryService.java
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
  src/main/java/com/hyperlink/server/domain/content/dto/ContentResponse.java
  src/main/java/com/hyperlink/server/domain/content/dto/RecommendationCompanyResponse.java
  src/main/java/com/hyperlink/server/domain/content/exception/CategoryAndCreatorIdConstraintViolationException.java
  src/main/java/com/hyperlink/server/domain/content/exception/InvalidSortException.java
  src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
  src/main/java/com/hyperlink/server/domain/memberContent/application/MemberContentService.java
  src/main/java/com/hyperlink/server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
  src/test/java/com/hyperlink/server/memberHistory/controller/MemberHistoryControllerTest.java
Labels: Feature

#149 [#139] 프로필 이미지 변경 api 구현
  build.gradle
  src/main/java/com/hyperlink/server/domain/member/controller/MemberController.java
  src/main/java/com/hyperlink/server/domain/member/domain/entity/Member.java
  src/main/java/com/hyperlink/server/domain/member/dto/ProfileImgResponse.java
  src/main/java/com/hyperlink/server/domain/member/exception/ProfileImgUploadFailException.java
  src/main/java/com/hyperlink/server/domain/member/s3/AwsS3Service.java
  src/main/java/com/hyperlink/server/global/config/AwsS3Config.java
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerMockTest.java
Labels: Feature

#153 [#152] 로그인 및 토큰 재발급시 관리자인지 확인하는 필드 추가
  src/main/java/com/hyperlink/server/domain/auth/application/AuthService.java
  src/main/java/com/hyperlink/server/domain/auth/controller/AuthController.java
  src/main/java/com/hyperlink/server/domain/auth/dto/LoginResponse.java
  src/main/java/com/hyperlink/server/domain/auth/dto/LoginResult.java
  src/main/java/com/hyperlink/server/domain/auth/dto/RenewResponse.java
  src/main/java/com/hyperlink/server/domain/auth/dto/RenewResult.java
  src/main/java/com/hyperlink/server/domain/auth/token/RefreshTokenCookieProvider.java
  src/test/java/com/hyperlink/server/auth/application/AuthServiceTest.java
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java
Labels: Refactor

#162 [#161] 검색 API 메소드 맵핑 오류 수정
  src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
Labels: Fix

#163 [#160] 구독 피드 목록 조회 API 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
  src/main/java/com/hyperlink/server/domain/subscription/application/SubscriptionService.java
  src/main/java/com/hyperlink/server/domain/subscription/controller/SubscriptionController.java
  src/main/java/com/hyperlink/server/domain/subscription/domain/SubscriptionRepository.java
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
  src/test/java/com/hyperlink/server/subscription/application/SubscriptionServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/subscription/controller/SubscriptionControllerTest.java
Labels: Feature

#166 [#165] 검색 querydsl 메소드 size 쿼리 수정
  src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
Labels: Refactor

#168 [#167] 패키지 위치 변경, 기타 오류 수정
  src/main/java/com/hyperlink/server/domain/memberHistory/application/MemberHistoryService.java
  src/main/java/com/hyperlink/server/domain/memberHistory/domain/MemberHistoryRepository.java
  src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
  src/test/java/com/hyperlink/server/memberContent/controller/MemberContentControllerTest.java
  src/test/java/com/hyperlink/server/memberContent/repository/MemberContentRespositoryTest.java
  src/test/java/com/hyperlink/server/memberHistory/application/MemberHistoryIntegrationTest.java
Labels: Test, Fix

#170 [#169] CreatorService transaction 오류 수정
  src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
Labels: Fix

#177 [#129] 데일리브리핑 API 구현 및 테스트 코드 작성
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/ServerApplication.java
  src/main/java/com/hyperlink/server/domain/category/domain/CategoryRepository.java
  src/main/java/com/hyperlink/server/domain/category/domain/vo/CategoryType.java
  src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
  src/main/java/com/hyperlink/server/domain/content/domain/ContentRepository.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/DailyBriefingScheduler.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/controller/DailyBriefingController.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/CountStatisticsByCategory.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/StatisticsType.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/dto/DailyBriefing.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/dto/GetDailyBriefingResponse.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/dto/StatisticsByCategoryResponse.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/infrastructure/DailyBriefingRepositoryCustom.java
  src/main/java/com/hyperlink/server/domain/member/domain/MemberRepository.java
  src/main/java/com/hyperlink/server/domain/memberHistory/domain/MemberHistoryRepository.java
  src/main/java/com/hyperlink/server/global/config/RedisConfig.java
  src/test/java/com/hyperlink/server/dailyBriefing/application/DailyBriefingServiceUnitTest.java
  src/test/java/com/hyperlink/server/dailyBriefing/controller/DailyBriefingControllerTest.java
  src/test/java/com/hyperlink/server/dailyBriefing/domain/vo/CountStatisticsByCategoryTest.java
  src/test/java/com/hyperlink/server/dailyBriefing/infrastructure/DailyBriefingRepositoryCustomTest.java
Labels: Feature, Test

#179 [#178] addView() Optional 인자를 Long으로 변경
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
Labels: Test, Refactor

#171 [#157] 회사이메일 인증번호 요청 api
  build.gradle
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java
  src/main/java/com/hyperlink/server/domain/company/controller/CompanyController.java
  src/main/java/com/hyperlink/server/domain/company/dto/MailRequest.java
  src/main/java/com/hyperlink/server/domain/company/exception/MailAuthInvalidException.java
  src/main/java/com/hyperlink/server/domain/company/mail/MailAuth.java
  src/main/java/com/hyperlink/server/domain/company/mail/MailAuthRepository.java
  src/main/java/com/hyperlink/server/domain/member/controller/MemberController.java
  src/main/java/com/hyperlink/server/domain/member/domain/entity/Member.java
  src/test/java/com/hyperlink/server/company/application/CompanyServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/company/controller/CompanyControllerTest.java
  src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
Labels: Feature

#188 [#187] RabbitMQ 통합 테스트 코드 수정
  src/test/java/com/hyperlink/server/content/controller/ContentRabbitMQIntegrationTest.java
Labels: Fix, Refactor

#181 [#164] 카테고리별 크리에이터 목록 조회
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
  src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
  src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRepository.java
  src/main/java/com/hyperlink/server/domain/creator/dto/CreatorAndSubscriptionCountMapper.java
  src/main/java/com/hyperlink/server/domain/creator/dto/CreatorResponse.java
  src/main/java/com/hyperlink/server/domain/creator/dto/CreatorsRetrievalResponse.java
  src/main/java/com/hyperlink/server/domain/creator/dto/SubscribeFlagMapper.java
  src/main/java/com/hyperlink/server/domain/subscription/domain/SubscriptionRepository.java
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
  src/test/java/com/hyperlink/server/creator/application/CreatorServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
  src/test/java/com/hyperlink/server/creator/domain/CreatorRepositoryTest.java
Labels: Feature

#186 [#182] 크리에이터 상세 정보 조회 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
  src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
  src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRepository.java
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
  src/test/java/com/hyperlink/server/company/application/CompanyServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/creator/application/CreatorServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
Labels: Feature

#191 [#190]: attentionCategory 변경시 이전 관심목록이 남아있던 문제 해결
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/attentionCategory/application/AttentionCategoryService.java
  src/main/java/com/hyperlink/server/domain/attentionCategory/controller/AttentionCategoryController.java
  src/main/java/com/hyperlink/server/domain/attentionCategory/domain/AttentionCategoryRepository.java
  src/main/java/com/hyperlink/server/domain/member/application/MemberService.java
  src/main/java/com/hyperlink/server/domain/member/controller/MemberController.java
  src/test/java/com/hyperlink/server/attentionCategory/application/AttentionCategoryServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/attentionCategory/controller/AttentionCategoryControllerTest.java
  src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerMockTest.java
Labels: Fix

#200 [#183] [어드민 페이지] 크리에이터 전체 조회 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
  src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
  src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRepository.java
  src/main/java/com/hyperlink/server/domain/creator/dto/CreatorAdminResponse.java
  src/main/java/com/hyperlink/server/domain/creator/dto/CreatorAdminResponses.java
  src/test/java/com/hyperlink/server/creator/application/CreatorServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
Labels: Feature

#209 [#208] HOTFIX 구독 등록/취소 기능 수정
  src/main/java/com/hyperlink/server/domain/subscription/application/SubscriptionService.java
Labels: Fix

#189 [#176] 좋아요 클릭 api 개발
  src/main/java/com/hyperlink/server/domain/common/ContentDtoFactoryService.java
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/domain/ContentRepository.java
  src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java
  src/main/java/com/hyperlink/server/domain/memberContent/application/BookmarkService.java
  src/main/java/com/hyperlink/server/domain/memberContent/application/LikeService.java
  src/main/java/com/hyperlink/server/domain/memberContent/controller/MemberContentController.java
  src/main/java/com/hyperlink/server/domain/memberContent/domain/MemberContentRepository.java
  src/main/java/com/hyperlink/server/domain/memberContent/dto/LikeClickRequest.java
  src/main/java/com/hyperlink/server/domain/memberContent/exception/LikeExistedException.java
  src/main/java/com/hyperlink/server/domain/memberContent/exception/LikeNotFoundException.java
  src/test/java/com/hyperlink/server/memberContent/application/BookmarkServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/memberContent/application/LikeServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/memberContent/application/LikeServiceMultiThreadTest.java
  src/test/java/com/hyperlink/server/memberContent/controller/MemberContentControllerTest.java
Labels: Feature

#202 [#192] 관심 카테고리 조회 api
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/attentionCategory/application/AttentionCategoryService.java
  src/main/java/com/hyperlink/server/domain/attentionCategory/controller/AttentionCategoryController.java
  src/main/java/com/hyperlink/server/domain/attentionCategory/domain/AttentionCategoryRepository.java
  src/main/java/com/hyperlink/server/domain/member/exception/ProfileImgUploadFailException.java
  src/test/java/com/hyperlink/server/attentionCategory/application/AttentionCategoryServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/attentionCategory/controller/AttentionCategoryControllerTest.java
  src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java
Labels: Feature

#175 [#172] 회사 이메일 인증 확인 및 등록
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java
  src/main/java/com/hyperlink/server/domain/company/controller/CompanyController.java
  src/main/java/com/hyperlink/server/domain/company/domain/CompanyRepository.java
  src/main/java/com/hyperlink/server/domain/company/domain/entity/Company.java
  src/main/java/com/hyperlink/server/domain/company/dto/MailAuthVerifyRequest.java
  src/main/java/com/hyperlink/server/domain/company/exception/CompanyNotFoundException.java
  src/main/java/com/hyperlink/server/domain/company/mail/MailAuth.java
  src/main/java/com/hyperlink/server/domain/member/application/MemberService.java
  src/main/java/com/hyperlink/server/domain/member/domain/entity/Member.java
  src/test/java/com/hyperlink/server/company/application/CompanyServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/company/controller/CompanyControllerTest.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
Labels: Feature

#218 [#217] 어드민 페이지 크리에이터 전체조회 페이지네이션의 현재 페이지값 변경
  src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
Labels: Fix

#211 [#207] 어드민 페이지 회사목록 조회 api 개발
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java
  src/main/java/com/hyperlink/server/domain/company/controller/CompanyController.java
  src/main/java/com/hyperlink/server/domain/company/domain/CompanyRepository.java
  src/main/java/com/hyperlink/server/domain/company/domain/entity/Company.java
  src/main/java/com/hyperlink/server/domain/company/dto/CompanyPageResponse.java
  src/main/java/com/hyperlink/server/domain/company/dto/CompanyResponse.java
  src/test/java/com/hyperlink/server/company/application/CompanyServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/company/controller/CompanyControllerTest.java
Labels: Feature

#206 [#203] 북마크 전체조회 api 개발
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/dto/BookMarkedContentPageResponse.java
  src/main/java/com/hyperlink/server/domain/memberContent/application/BookmarkService.java
  src/main/java/com/hyperlink/server/domain/memberContent/application/LikeService.java
  src/main/java/com/hyperlink/server/domain/memberContent/controller/MemberContentController.java
  src/main/java/com/hyperlink/server/domain/memberContent/domain/MemberContentRepository.java
  src/main/java/com/hyperlink/server/domain/memberContent/domain/entity/MemberContent.java
  src/main/java/com/hyperlink/server/domain/memberContent/dto/BookmarkPageResponse.java
  src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/memberContent/application/BookmarkServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/memberContent/application/LikeServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/memberContent/controller/MemberContentControllerTest.java
Labels: Feature

#219 [#212] 회사를 추천 서비스에 추가하는 api 개발
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java
  src/main/java/com/hyperlink/server/domain/company/controller/CompanyController.java
  src/main/java/com/hyperlink/server/domain/company/domain/entity/Company.java
  src/test/java/com/hyperlink/server/company/application/CompanyServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/company/controller/CompanyControllerTest.java
Labels: Feature

#224 [#223] company 추천서비스 여부 변경 api uri 수정
  src/main/java/com/hyperlink/server/domain/company/controller/CompanyController.java
  src/test/java/com/hyperlink/server/company/controller/CompanyControllerTest.java
Labels: Fix

#226 [#225] 회사 조회 api page기준값 수정
  src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java
  src/test/java/com/hyperlink/server/company/application/CompanyServiceIntegrationTest.java
Labels: Refactor

#239 [#238] redisTemplate Value Object로 변경
  src/main/java/com/hyperlink/server/domain/dailyBriefing/DailyBriefingScheduler.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java
  src/main/java/com/hyperlink/server/global/config/RedisConfig.java
Labels: Feature

#229 [#213] 인가 필터 개발 및 필터 예외처리 수정
  src/main/java/com/hyperlink/server/domain/auth/token/AuthTokenExtractor.java
  src/main/java/com/hyperlink/server/domain/member/application/MemberService.java
  src/main/java/com/hyperlink/server/global/config/WebConfig.java
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
  src/main/java/com/hyperlink/server/global/filter/AuthorizationFilter.java
  src/test/java/com/hyperlink/server/AuthSetupForMock.java
  src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java
Labels: Feature

#232 [#220] auth api 로그인 및 회원가입시 googleAccessToken 만료시키기
  src/main/java/com/hyperlink/server/domain/auth/application/AuthService.java
  src/main/java/com/hyperlink/server/domain/auth/controller/AuthController.java
  src/main/java/com/hyperlink/server/domain/auth/controller/AuthControllerMockTest.java
  src/main/java/com/hyperlink/server/domain/auth/oauth/GoogleOauthClient.java
  src/main/java/com/hyperlink/server/domain/member/controller/MemberController.java
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerMockTest.java
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerMockTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
Labels: Refactor

#233 [#230] Content dto에 로그인 멤버의 Like여부 확인해서 전달하기
  src/main/java/com/hyperlink/server/domain/common/ContentDtoFactoryService.java
Labels: Refactor

#237 [#235] 회사 이름 변경 api 개발
  src/docs/asciidoc/api.adoc
  src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java
  src/main/java/com/hyperlink/server/domain/company/controller/CompanyController.java
  src/main/java/com/hyperlink/server/domain/company/domain/entity/Company.java
  src/main/java/com/hyperlink/server/domain/company/dto/CompanyChangeNameRequest.java
  src/test/java/com/hyperlink/server/company/application/CompanyServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/company/controller/CompanyControllerTest.java
Labels: Feature

#241 [#240] spring batch metadata tables create
  src/main/resources/db/migration/V23__spring_batch_table_init.sql
Labels: Feature, Environment

#248 [#247] 배치 작업 수동실행 어드민 API 구현
  src/main/java/com/hyperlink/server/domain/admin/controller/AdminController.java
  src/main/java/com/hyperlink/server/domain/notRecommendCreator/domain/NotRecommendCreatorRepository.java
  src/main/java/com/hyperlink/server/domain/subscription/domain/SubscriptionRepository.java
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
Labels: Feature, Fix

#250 [#249] 배치 작업 수동 실행 API url 변경
  src/main/java/com/hyperlink/server/domain/admin/controller/AdminController.java
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
Labels: Fix

#252 [#251] 검색 API 전체 사이즈 에러 수정
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
Labels: Fix

#255 [#254] 인가 필터에서 options 메소드 허용시키기
  src/main/java/com/hyperlink/server/global/filter/AuthorizationFilter.java
Labels: Fix

#242 [#205] 회사 또는 나이대에 대한 추천 기능 구현
  src/main/java/com/hyperlink/server/domain/common/ContentDtoFactoryService.java
  src/main/java/com/hyperlink/server/domain/content/domain/service/ContentViewerAgeAndGenderRecommender.java
  src/main/java/com/hyperlink/server/domain/content/domain/service/ContentViewerCompanyRecommender.java
  src/main/java/com/hyperlink/server/domain/content/domain/service/ContentViewerNoneRecommender.java
  src/main/java/com/hyperlink/server/domain/content/domain/service/ContentViewerRecommender.java
  src/main/java/com/hyperlink/server/domain/content/domain/service/ContentViewerRecommenderFactory.java
  src/main/java/com/hyperlink/server/domain/content/dto/ContentResponse.java
  src/main/java/com/hyperlink/server/domain/content/dto/ContentViewerRecommendationResponse.java
  src/main/java/com/hyperlink/server/domain/content/dto/RecommendationCompanyResponse.java
  src/main/java/com/hyperlink/server/domain/content/exception/InvalidAgeException.java
  src/main/java/com/hyperlink/server/domain/content/exception/InvalidGenderException.java
  src/main/java/com/hyperlink/server/domain/memberContent/domain/MemberContentRepository.java
  src/main/java/com/hyperlink/server/domain/memberContent/dto/ContentViewerAgeAndGenderRecommendDto.java
  src/main/java/com/hyperlink/server/domain/memberContent/dto/ContentViewerCompanyRecommendDto.java
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
  src/test/java/com/hyperlink/server/memberHistory/controller/MemberHistoryControllerTest.java
  src/test/java/com/hyperlink/server/subscription/controller/SubscriptionControllerTest.java
Labels: Feature

#257 [#253] 데일리브리핑 API 응답 데이터 추가
  src/main/java/com/hyperlink/server/domain/content/domain/ContentRepository.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/controller/DailyBriefingScheduler.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/ContentStatisticsRepository.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/ContentStatistics.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/CountStatisticsByCategory.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/DailyBriefing.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/MemberStatistics.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/ViewStatistics.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/dto/DailyBriefing.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/dto/GetDailyBriefingResponse.java
  src/main/java/com/hyperlink/server/domain/memberHistory/domain/MemberHistoryRepository.java
  src/test/java/com/hyperlink/server/dailyBriefing/application/DailyBriefingServiceUnitTest.java
  src/test/java/com/hyperlink/server/dailyBriefing/controller/DailyBriefingControllerTest.java
Labels: Feature, Test

#245 [#244] 북마크 전체조회 dto 변경
  src/main/java/com/hyperlink/server/domain/content/dto/BookMarkedContentPageResponse.java
  src/main/java/com/hyperlink/server/domain/content/dto/ContentResponse.java
  src/main/java/com/hyperlink/server/domain/memberContent/application/BookmarkService.java
  src/main/java/com/hyperlink/server/domain/memberContent/domain/MemberContentRepository.java
  src/main/java/com/hyperlink/server/domain/memberContent/dto/BookmarkPageResponse.java
  src/test/java/com/hyperlink/server/memberContent/application/BookmarkServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/memberContent/controller/MemberContentControllerTest.java
Labels: Refactor

#259 [#258] 테스트 오류 수정, 불필요한 파일 삭제
  src/main/java/com/hyperlink/server/domain/memberCreator/domain/entity/MemberCreator.java~[#61] memberCreator table 생성
  src/main/java/com/hyperlink/server/domain/memberCreator/domain/entity/MemberCreator.java~develop/v0.1
  src/test/java/com/hyperlink/server/content/domain/ContentRepositoryTest.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
Labels: Test, Fix

#265 [#264] 데일리브리핑 응답값 필드명 변경
  src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/MemberStatistics.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/ViewStatistics.java
Labels: Refactor

#267 [#266] 추천 크리에이터 조회 API RestDocs 작성
  src/docs/asciidoc/api.adoc
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
Labels: Test

#270 [#268] 추천 크리에이터 조회 API 비회원 요청 금지
  src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
  src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRecommendService.java
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
Labels: Feature, Refactor

#277 [#260] 조회수 갱신 API 유저 행동패턴 파라미터 추가
  src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
  src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
  src/main/java/com/hyperlink/server/domain/memberHistory/application/MemberHistoryService.java
  src/main/java/com/hyperlink/server/domain/memberHistory/domain/entity/MemberHistory.java
  src/main/resources/db/migration/V24__add_column_is_search.sql
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
  src/test/java/com/hyperlink/server/memberHistory/application/MemberHistoryIntegrationTest.java
Labels: Feature, Test

#285 [#284] 데일리브리핑 데이터 redis expire 설정
  src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/controller/DailyBriefingScheduler.java
Labels: Feature

#279 [#278] 필터 오류 응답 한글깨짐 해결
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
  src/main/java/com/hyperlink/server/global/filter/AuthorizationFilter.java
Labels: Fix

#287 [#286] mockMvc테스트에 추가된 char-set=utf-8 추가
  src/test/java/com/hyperlink/server/attentionCategory/controller/AttentionCategoryControllerTest.java
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerMockTest.java
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerMockTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
Labels: Test, Fix

#289 [#288] mockMvc utf-8 타입 추가
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerMockTest.java
Labels: Fix

#291 [#286] Filter 메시지 한글깨짐 문제 해결
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
  src/main/java/com/hyperlink/server/global/filter/AuthorizationFilter.java
Labels: Fix

#293 utf-8 테스트 코드 수정
  src/main/java/com/hyperlink/server/domain/auth/controller/AuthControllerMockTest.java
  src/test/java/com/hyperlink/server/attentionCategory/controller/AttentionCategoryControllerTest.java
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerMockTest.java
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerMockTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
Labels: Test, Fix

#294 필터 401 메시지 한글 깨짐 문제 해결
  src/main/java/com/hyperlink/server/domain/auth/controller/AuthControllerMockTest.java
  src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
  src/main/java/com/hyperlink/server/global/filter/AuthorizationFilter.java
  src/test/java/com/hyperlink/server/attentionCategory/controller/AttentionCategoryControllerTest.java
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerMockTest.java
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerMockTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
Labels: Test, Fix

#296 [#295] 회사 인증 dto 유효성 변경
  src/main/java/com/hyperlink/server/domain/company/controller/CompanyController.java
  src/main/java/com/hyperlink/server/domain/company/dto/MailAuthVerifyRequest.java
Labels: Fix

#297 [#295] 회사 인증 dto 변경
  src/main/java/com/hyperlink/server/domain/company/dto/MailAuthVerifyRequest.java
Labels: Fix

#299 [#298] 프론트 임시 배포 도메인 origin 추가
  src/main/java/com/hyperlink/server/global/config/WebConfig.java
Labels: Fix

#303 [#201] isViewable 한 컨텐츠만 메인페이지에서 조회할 수 있도록 변경하기
  src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
  src/main/resources/static/docs/api.html
Labels: Fix

#304 [#302] loginMemberArgumentResolver에서 토큰 존재하지만 유효하지않을경우 empty값 반환
  src/main/java/com/hyperlink/server/domain/auth/application/AuthService.java
  src/main/java/com/hyperlink/server/domain/auth/token/AuthTokenExtractor.java
Labels: Fix

#305 [#201] isViewable 한 컨텐츠만 메인페이지에서 조회할 수 있도록 변경하기
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
Labels: Fix

#308 [#302] extractMemberIdInCorrectTest empty값 반환으로 수정
  src/test/java/com/hyperlink/server/auth/token/AuthTokenExtractorTest.java
Labels: Fix

#307 [#262] 히스토리 전체 내역 조회 중복값 제거
  src/main/java/com/hyperlink/server/domain/memberHistory/application/MemberHistoryService.java
  src/main/java/com/hyperlink/server/domain/memberHistory/controller/MemberHistoryController.java
  src/main/java/com/hyperlink/server/domain/memberHistory/domain/MemberHistoryRepository.java
Labels: Fix

#310 [#309] 추천 크리에이터 조회 API 응답 중복값 제거
  src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRecommendService.java
Labels: Fix

#313 [#201] isViewable 한 글만 볼 수 있도록 변경
  src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
  src/test/java/com/hyperlink/server/subscription/application/SubscriptionServiceIntegrationTest.java
Labels: Feature

#315 [#312] 회사 이메일 인증 api dto 로고uri 필드 제거
  src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java
  src/main/java/com/hyperlink/server/domain/company/domain/entity/Company.java
  src/main/java/com/hyperlink/server/domain/company/dto/MailAuthVerifyRequest.java
  src/test/java/com/hyperlink/server/company/application/CompanyServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/company/controller/CompanyControllerTest.java
  src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
Labels: Refactor

#275 [#269] 로그아웃, access-token 재발급 api restdocs 적용
  build.gradle
  src/docs/asciidoc/api.adoc
  src/test/java/com/hyperlink/server/AuthSetupForMock.java
  src/test/java/com/hyperlink/server/auth/controller/AuthControllerMockTest.java
  src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
Labels: Test, Refactor

#316 [#314] 🚨HOTFIX🚨 구독하지 않았을 때 모든 글이 보이는 문제 해결
  src/main/java/com/hyperlink/server/domain/subscription/application/SubscriptionService.java
Labels: Fix

#320 [#318] company Optional.orget() 수정
  src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java
Labels: Fix

#321 [#319] [Admin] 크리에이터 조회 페이지 프로필 이미지 링크 전송하도록 변경
  src/main/java/com/hyperlink/server/domain/creator/dto/CreatorAdminResponse.java
  src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
Labels: Fix

#323 [#322] 북마크 전체조회시 isLiked 항상 false인 문제 해결
  src/main/java/com/hyperlink/server/domain/memberContent/application/BookmarkService.java
Labels: Fix

#326 [#325] 크리에이터 추천풀이 아직 생성 안된 회원의 경우 랜덤으로 응답하기
  src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRecommendService.java
  src/main/resources/static/docs/api.html
Labels: Feature, Fix

#327 [#325] main으로 머지 🐥
  src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRecommendService.java
  src/main/resources/static/docs/api.html
Labels: Feature, Fix

#329 [#328] 데일리브리핑 redis key 값 오류 수정
  src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java
Labels: Fix

#332 [#331] 데일리브리핑 컨텐츠 증가분 조회 에러 수정
  src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/ContentStatistics.java
Labels: Fix

#333 🎣 데일리브리핑 일자별 컨텐츠 증가분 조회 에러 수정
  src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java
  src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/ContentStatistics.java
Labels: Fix

#335 [#334] HOTFIX 게시글이 중복되어 보이는 문제 발생
  src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
  src/main/resources/static/docs/api.html
Labels: Fix

#336 HOTFIX 게시글 중복 해결 & READ.ME 파일 추가
  README.md
  src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
  src/main/resources/static/docs/api.html
Labels: Fix

#337 [#262] 검색 응답 페이지 정렬 기준 변경
  src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
  src/test/java/com/hyperlink/server/content/domain/ContentRepositoryTest.java
Labels: Feature

#339 [#338] 불필요한 코드 잘못 들어간 것 삭제
  src/test/java/com/hyperlink/server/content/domain/ContentRepositoryTest.java
Labels: Fix

#344 [#343] 검색 메서드 오류 수정
  src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
  src/test/java/com/hyperlink/server/TestConfig.java
  src/test/java/com/hyperlink/server/content/domain/ContentRepositoryTest.java
Labels: Test, Fix
